package com.taskApp.task.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PRODUCT_DETAIL".
 */
@Entity
public class ProductDetail {

    @Id(autoincrement = true)
    private Long id;
    private String productName;
    private Integer productCost;
    private Integer qauntity;
    private Integer totalPrice;
    private Boolean isActive;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ProductDetail() {
    }

    public ProductDetail(Long id) {
        this.id = id;
    }

    @Generated
    public ProductDetail(Long id, String productName, Integer productCost, Integer qauntity, Integer totalPrice, Boolean isActive) {
        this.id = id;
        this.productName = productName;
        this.productCost = productCost;
        this.qauntity = qauntity;
        this.totalPrice = totalPrice;
        this.isActive = isActive;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getProductCost() {
        return productCost;
    }

    public void setProductCost(Integer productCost) {
        this.productCost = productCost;
    }

    public Integer getQauntity() {
        return qauntity;
    }

    public void setQauntity(Integer qauntity) {
        this.qauntity = qauntity;
    }

    public Integer getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
